basic_settings:
  site_title: Energipartner Åland
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/white.png
  mobile_logo_image: /assets/img/brand/color.png
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Hem'
      url: /
    - title: 'Fröling värmepannor'
      url: '/produkter/'          
    - title: 'Referensprojekt'
      url: '/artiklar/'    
    - title: 'Om'
      url: '/om/'
    - title: 'Kontakt'
      url: '/kontakt/'

footer_settings:
  footer_tagline: Värme att lita på, lokal expertis på Åland

social_settings:
  facebook_url: 'https://www.facebook.com/energipartner.aland/'
  instagram_url: 'https://www.instagram.com/energipartner.aland'

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 